#!/bin/bash

# This small script only submits the FIRST job. After that, the batch launcher
# submits its own continuation jobs whenever a walltime checkpoint is saved.

# Examples:
#   # Use the defaults: 2 nodes and the default YAML config.
#   ./submit_diffusion_fsdp_Frontier_loop.sh
#
#   # Use 4 nodes (8 GPUs per node).
#   ./submit_diffusion_fsdp_Frontier_loop.sh 4
#
#   # Use 2 nodes and a different config.
#   ./submit_diffusion_fsdp_Frontier_loop.sh 2 /path/to/config.yaml
#
#   ./submit_diffusion_fsdp_Frontier_loop.sh [nodes] [config_file] [training_script]

# Stop immediately if this submission script has an error.
set -euo pipefail

# --- Read the optional command-line arguments --------------------------------
# With no arguments, request 2 nodes and use the project's default config.
NODES="${1:-2}"
CONFIG_FILE="${2:-}"
TRAINING_SCRIPT="${3:-}"

# --- Locate the batch launcher and default config ----------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LAUNCHER="${SCRIPT_DIR}/diffusion_fsdp_Frontier.sh"
CONFIG_FILE="${CONFIG_FILE:-${REPO_ROOT}/configs/xct/diffusion/base_config_dgx_2D.yaml}"
TRAINING_SCRIPT="${TRAINING_SCRIPT:-${REPO_ROOT}/dev_scripts/train_diffusion_fsdp_wFixedFID_2D_singMod.py}"

# --- Check the user's inputs before requesting expensive resources -----------
if [[ ! "$NODES" =~ ^[1-9][0-9]*$ ]]; then
    echo "Node count must be a positive integer: $NODES" >&2
    exit 2
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Config file not found: $CONFIG_FILE" >&2
    exit 2
fi

if [[ ! -f "$TRAINING_SCRIPT" ]]; then
    echo "Training script not found: $TRAINING_SCRIPT" >&2
    exit 2
fi

export TRAINING_SCRIPT

# Match the run directory generated by the Python training script, then keep
# Slurm stdout/stderr in that checkpoint's logs directory. The config values
# are simple scalars, so reading them here avoids requiring PyYAML on the login
# node merely to submit a job.
config_value() {
    local section="$1"
    local key="$2"
    awk -v wanted_section="$section" -v wanted_key="$key" '
        /^[[:alnum:]_]+:/ {
            current_section=$1
            sub(/:$/, "", current_section)
        }
        current_section == wanted_section && $1 == wanted_key ":" {
            value=$0
            sub(/^[^:]+:[[:space:]]*/, "", value)
            sub(/[[:space:]]*#.*/, "", value)
            gsub(/"/, "", value)
            print value
            exit
        }
    ' "$CONFIG_FILE"
}

CHECKPOINT_ROOT="$(config_value trainer checkpoint_root)"
FSDP_SIZE="$(config_value parallelism fsdp_size)"
TENSOR_PAR_SIZE="$(config_value parallelism tensor_par_size)"
SEQ_PAR_SIZE="$(config_value parallelism seq_par_size)"
LR="$(config_value model lr)"
PATCH_SIZE="$(config_value model patch_size)"
BATCH_SIZE="$(config_value data batch_size)"
EMBED_DIM="$(config_value model embed_dim)"
DATA_TYPE="$(config_value trainer data_type)"
JOB_NAME="xct_f${FSDP_SIZE}_t${TENSOR_PAR_SIZE}_${DATA_TYPE}"
export JOB_NAME

WORLD_SIZE=$((NODES * 8))
PARALLEL_FACTOR=$((FSDP_SIZE * TENSOR_PAR_SIZE * SEQ_PAR_SIZE))
if (( WORLD_SIZE % PARALLEL_FACTOR != 0 )); then
    echo "World size ${WORLD_SIZE} is not divisible by parallel factor ${PARALLEL_FACTOR}" >&2
    exit 2
fi
SIMPLE_DDP_SIZE=$((WORLD_SIZE / PARALLEL_FACTOR))
RUN_NAME="N${NODES}_G${WORLD_SIZE}_DDP${SIMPLE_DDP_SIZE}_FSDP${FSDP_SIZE}_TP${TENSOR_PAR_SIZE}_lr${LR}_PS${PATCH_SIZE}_BS${BATCH_SIZE}_ED${EMBED_DIM}_${DATA_TYPE}"
LOG_DIR="${CHECKPOINT_ROOT}/${RUN_NAME}/logs"
mkdir -p "$LOG_DIR"
export LOG_DIR

# --- Submit the first job -----------------------------------------------------
# The first job starts from scratch. The batch launcher changes the effective
# resume setting to True when it submits every later continuation.
echo "Submitting initial ${NODES}-node job with automatic continuation enabled."
echo "Config: ${CONFIG_FILE}"
echo "Training script: ${TRAINING_SCRIPT}"
echo "Logs: ${LOG_DIR}"
sbatch \
    --nodes="$NODES" \
    --job-name="$JOB_NAME" \
    --output="${LOG_DIR}/%x-%j.out" \
    --error="${LOG_DIR}/%x-%j.out" \
    --export=ALL,AUTO_RESUBMIT=1,RESUME_FROM_CHECKPOINT=False \
    "$LAUNCHER" "$CONFIG_FILE"
