# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32"
  checkpoint_path: "../../checkpoint/imagenet/mae/base"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  loss_fn: "MSE"

  net:
    init_args:
      default_vars: [
        "red",
        "green",
        "blue",
      ]
      tile_size: [256, 256]
      patch_size: 16
      embed_dim: 768
      depth: 12
      num_heads: 12
      decoder_embed_dim: 512
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio: 4
      mlp_ratio_decoder: 4
      drop_path: 0.0
      drop_rate: 0.0
      mask_ratio: 0.75
      linear_decoder: False
      twoD: True
      use_varemb: False
      adaptive_patching: False
      fixed_length: 196
      separate_channels: False

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "imagenet"
  dict_root_dirs: {
    'imagenet': '/lustre/orion/nro108/world-shared/enzhi/dataset/imagenet/train',
  }
  dict_start_idx: {
    'imagenet': 0,
  }
  dict_end_idx: {
    'imagenet': 1,
  }
  dict_buffer_sizes: {
    'imagenet': 100,
  }
  num_channels_available: {
    'imagenet': 3,
  }
  num_channels_used: {
    'imagenet': 3,
  }
  dict_in_variables: {
    'imagenet': [
     "red", 
     "green", 
     "blue", 
    ],
  }
  batch_size: 32
  num_workers: 1
  pin_memory: False
  single_channel: False
  tile_overlap: 0.0
  use_all_data: False

# ---------------------------- DATASET SPECIFIC OPTIONS -------------------------------------------
dataset_options:

  imagenet_resize: {
      'imagenet': [256,256],
    }

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  batches_per_rank_epoch: {
    'imagenet': 4935,
  }
  dataset_group_list: '1:1:1:1:1:1:1:1'
