# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32"
  checkpoint_path: "../../checkpoint/sst/pred/bigger"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False
  use_pretrained_mae_model: False
  mae_checkpoint_path: "../../checkpoint/sst/mae/bigger"
  mae_checkpoint_filename: "multi_last_odd" #multi_last_odd or multi_last_even

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.00001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8

  net:
    init_args:
      default_vars: [
        "u",
        "v",
        "w",
        "r",
      ]
      tile_size: [64, 64, 64]
      patch_size: 4
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4
      drop_path: 0.0
      linear_decoder: False
      twoD: False
      use_varemb: False
      feature_size: 16
      skip_connection: False

      decoder_embed_dim: 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio_decoder: 4
      mask_ratio: 0.75

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "sst"
  dict_root_dirs: {
    'P1F2R96': '/lustre/orion/world-shared/stf006/muraligm/CFD135/data_iso/max_ent/binary_data/P1F2R96/UCF-ViT/train',
    'P1F3R96': '/lustre/orion/world-shared/stf006/muraligm/CFD135/data_iso/max_ent/binary_data/P1F3R96/UCF-ViT/train',
    'P1F4R96': '/lustre/orion/world-shared/stf006/muraligm/CFD135/data_iso/max_ent/binary_data/P1F4R96/UCF-ViT/train',
  }
  dict_start_idx: {
    'P1F2R96': 0,
    'P1F3R96': 0,
    'P1F4R96': 0,
  }
  dict_end_idx: {
    'P1F2R96': 1,
    'P1F3R96': 1,
    'P1F4R96': 1,
  }
  dict_buffer_sizes: {
    'P1F2R96': 100,
    'P1F3R96': 100,
    'P1F4R96': 100,
  }
  num_channels_used: {
    'P1F2R96': 4,
    'P1F3R96': 4,
    'P1F4R96': 4,
  }
  dict_in_variables: {
    'P1F2R96': [
     "u", 
     "v", 
     "w", 
     "r", 
    ],
    'P1F3R96': [
     "u", 
     "v", 
     "w", 
     "r", 
    ],
    'P1F4R96': [
     "u", 
     "v", 
     "w", 
     "r", 
    ],
  }
  batch_size: 2
  num_workers: 1
  pin_memory: False
  single_channel: False
  tile_overlap: 0.0
  use_all_data: False
  num_classes: 1 #We're prediciting with MSE so use num_classes=1

# ---------------------------- DATASET SPECIFIC OPTIONS -------------------------------------------
dataset_options:

  nx: {
    'P1F2R96': 1024,
    'P1F3R96': 1024,
    'P1F4R96': 1024,
  }
  ny: {
    'P1F2R96': 1024,
    'P1F3R96': 1024,
    'P1F4R96': 1024,
  }
  nz: {
    'P1F2R96': 512,
    'P1F3R96': 512,
    'P1F4R96': 512,
  }
  nx_skip: {
    'P1F2R96': 1,
    'P1F3R96': 1,
    'P1F4R96': 1,
  }
  ny_skip: {
    'P1F2R96': 1,
    'P1F3R96': 1,
    'P1F4R96': 1,
  }
  nz_skip: {
    'P1F2R96': 1,
    'P1F3R96': 1,
    'P1F4R96': 1,
  }

  dict_out_variables: {
    'P1F2R96': [
     "r", 
    ],
    'P1F3R96': [
     "r", 
    ],
    'P1F4R96': [
     "r", 
    ],
  }

  chunk_size: {
    'P1F2R96': [512,512,256],
    'P1F3R96': [512,512,256],
    'P1F4R96': [512,512,256],
  }


# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  auto_load_balancing: True
  batches_per_rank_epoch: {
  'P1F2R96': 358912,
  'P1F3R96': 239232,
  'P1F4R96': 239232,
  }
  dataset_group_list: '2:3:3'
