# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 20000
  data_type: "float32" #"bfloat16" #
  gpu_type: "nvidia"
  checkpoint_path: "/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D_AllModalities_SingleClass/285K_data/256x256x256/Pat2000_Dec0.9/N1_20PercentData_Adaptivelr0.005_P8_BS512_ED1024_float32_redo" 
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Diverse_Concrete_256x256_standardized/16800Vols/256x256x256/Pat2000_Dec0.9/N2_Adaptivelr0.006_P8_BS256_ED1024_float32" 
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_Synth/1200Vols/32x32x32_3levels0to1/Pat2000_Dec0.9_OneGPUs/N1_GPU1_Adaptivelr0.00001_P1m_BS256_ED1024_float32"
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_normalized/600Vols/256x256x256/Pat2000_Dec0.9/N16_Adaptivelr0.001_P8_BS256_ED2048_float32" 
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_Synth/1200Vols/32x32x32/Pat200000_Dec0.9_OneGPU/N1_GPU1_Adaptivelr0.00001_P1_BS256_ED1024_float32"
  ##32x32x32/32Node_lr0.01_Patch8_batch1" # 
  checkpoint_filename: "XCT_Conc_Norm_base" # "XCT_Conc_base_Synth" # "Breaker_AM_base" # "XCT_half_concrete_base" #  
  checkpoint_filename_for_loading: "XCT_Conc_Norm_base_0" # "XCT_Conc_base_Synth_0" #  "Breaker_AM_base_0" #  "XCT_half_concrete_base_0" #  xct_concrete_base_[EPOCH]
  inference_path: "/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D_AllModalities_SingleClass/285K_data/256x256x256/Pat2000_Dec0.9/N1_20PercentData_Adaptivelr0.005_P8_BS512_ED1024_float32_redo"
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Diverse_Concrete_256x256_standardized/16800Vols/256x256x256/Pat2000_Dec0.9/N2_Adaptivelr0.006_P8_BS256_ED1024_float32" 
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_Synth/1200Vols/32x32x32_3levels0to1/Pat2000_Dec0.9_OneGPUs/N1_GPU1_Adaptivelr0.00001_P1m_BS256_ED1024_float32/inference"
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_normalized/600Vols/256x256x256/Pat2000_Dec0.9/N16_Adaptivelr0.001_P8_BS256_ED2048_float32/inference"
  #"/lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_Synth/1200Vols/32x32x32/Pat200000_Dec0.9_OneGPU/N1_GPU1_Adaptivelr0.00001_P1_BS256_ED1024_float32/inference"
  # #/32x32x32/32Node_lr0.01_Patch8_batch1/inference"
  # /lustre/fs0/scratch/ziabariak/checkpoint/xct/diffusion/base/full_2D/XCT_Conc_Synth/1200Vols/32x32x32/Pat200000_Dec0.9_OneGPU/N1_GPU1_Adaptivelr0.00001_P1_BS256_ED1024_float32
  resume_from_checkpoint: False

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8  #num of nodes * gpus
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.005
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  loss_fn: "MSE"
  use_grad_scaler: False #True

  net:
    init_args:
      default_vars: [
        "xct", 
      ]
      tile_size: [256, 256, 256] #[32,32,32] #
      patch_size: 8 #8 # 1
      embed_dim: 1024 #512 #1024
      depth: 8 # 10
      num_heads: 8
      decoder_embed_dim: 1024 # 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio: 6
      mlp_ratio_decoder: 4
      drop_path: 0.1
      drop_rate: 0.0  # 0.05 # 
      linear_decoder: True
      twoD: True
      use_varemb: False
      adaptive_patching: False
      fixed_length: 196
      separate_channels: False
      num_time_steps: 1000

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "xct"
  dict_root_dirs: {
    'xct1': "/lustre/fs0/scratch/ziabariak/ALL_256x256x256_data",
    # 'xct1': '/lustre/fs0/scratch/lyngaasir/DiffusiveINR_Data/XCT_Concrete_Z00730_650Files_standardized',
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/NeutronCT_Concrete_256x256x256_standardized/", # 1539 total, 600 -->0.3898
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/XCT_Concrete_256x256_standardized", #16800
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/TRISO_Data/Triso_Data_256x256x256_standardized", #680
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/Breaker_data/256x256x256_standardized", # 5120 -->0.1328,
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/AM_ScattCorrected_data/AM_ScatterCorrected_Data_256x256x256_standardized", # 1022-->0.6654,
    # # 'xct1': '/lustre/fs0/scratch/lyngaasir/DiffusiveINR_Data/Normalized_Data/XCT_Concrete_Z00730_650Files_normalized', #599 #'/lustre/fs0/scratch/ziabariak/XCT_Concrete_32x32x32_Z00730', #
    # 'xct1': "/lustre/fs0/scratch/ziabariak/data_LDRD/XCT_NCT_Synth/Downsampled_128x128_128_beforeCrop/XCT_Concrete_32x32x32_Synth", #_artificallyStandardized/", 
    # 'xct1' : "/lustre/fs0/scratch/ziabariak/data_LDRD/XCT_NCT_Synth/Downsampled_128x128_128_beforeCrop/XCT_Concrete_32x32x32_Synth_standardized/",
    # 'xct1' : "/lustre/fs0/scratch/ziabariak/data_LDRD/XCT_NCT_Synth/Downsampled_128x128_128_beforeCrop/XCT_Concrete_32x32x32_Synth_Correct3levels_0to1/",
    }
  dict_start_idx: {
    'xct1': 0,
  }
  dict_end_idx: {
    'xct1': 0.2,
  }
  dict_buffer_sizes: {
    'xct1': 400,
  }
  num_channels_used: {
    'xct1': 1,
  }
  dict_in_variables: {
    'xct1': [
     "xct", 
    ],
  }
  batch_size: 512
  num_workers: 1
  pin_memory: False
  single_channel: False
  tile_overlap: 0.0
  use_all_data: False

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  auto_load_balancing: True
  batches_per_rank_epoch: {
  'xct1': 600,
  }
  dataset_group_list: '16' #'1:3:75:1:8:4' # '2:1' # '16' # 75:
