# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32"
  checkpoint_path: "../../checkpoint/basic_ct/sap/base"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False
  use_pretrained_mae_model: False
  mae_checkpoint_path: "../../checkpoint/basic_ct/mae/base"
  mae_checkpoint_filename: "multi_last_odd" #multi_last_odd or multi_last_even

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8
  tensor_par_size: 1
  seq_par_size: 1
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8

  net:
    init_args:
      default_vars: [
        "ct_res1",
      ]
      tile_size: [64,64,64]
      patch_size: 4
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4
      drop_path: 0.0
      twoD: False
      use_varemb: False
      adaptive_patching: True
      fixed_length: 512
      separate_channels: False
      use_adaptive_pos_emb: True

      decoder_embed_dim: 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio_decoder: 4
      linear_decoder: False
      mask_ratio: 0.75

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "basic_ct"
  dict_root_dirs: {
    'ct1': '/lustre/orion/world-shared/nro108/anikat/dataset/Tr8_Training',
  }
  dict_start_idx: {
    'ct1': 0,
  }
  dict_end_idx: {
    'ct1': 1,
  }
  dict_buffer_sizes: {
    'ct1': 100,
  }
  num_channels_used: {
    'ct1': 1,
  }
  dict_in_variables: {
    'ct1': [
     "ct_res1", 
    ],
  }
  batch_size: 2
  num_workers: 1
  pin_memory: False
  single_channel: False
  tile_overlap: 0.0
  use_all_data: False
  num_classes: 4

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  auto_load_balancing: True
  batches_per_rank_epoch: {
    'ct1': 13568,
  }
  dataset_group_list: '8'
