# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32"
  checkpoint_path: "../../checkpoint/s8d_3d/mae/base"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False
  
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  loss_fn: "MSE"

  net:
    init_args:
      default_vars: [
        "ct_res1",
      ]
      #tile_size: [8192,8192]
      tile_size: [128,128,128]
      patch_size: 8
      embed_dim: 768
      depth: 12
      num_heads: 12
      decoder_embed_dim: 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio: 4
      mlp_ratio_decoder: 4
      drop_path: 0.0
      mask_ratio: 0.75
      linear_decoder: False
      twoD: False
      use_varemb: False
      adaptive_patching: True
      fixed_length: 4096
      separate_channels: False

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "s8d_3d"
  dict_root_dirs: {
    'No_000': '/lustre/orion/nro108/world-shared/enzhi/spring8data/large_demo/No_000',
    'No_001': '/lustre/orion/nro108/world-shared/enzhi/spring8data/large_demo/No_001',
  }
  dict_start_idx: {
    'No_000': 0,
    'No_001': 0,
  }
  dict_end_idx: {
    'No_000': 1,
    'No_001': 1,
  }
  dict_buffer_sizes: {
    'No_000': 100,
    'No_001': 100,
  }
  num_channels_available: {
    'No_000': 1,
    'No_001': 1,
  }
  num_channels_used: {
    'No_000': 1,
    'No_001': 1,
  }
  dict_in_variables: {
    'No_000': [
     "ct_res1", 
    ],
    'No_001': [
     "ct_res1", 
    ],
  }
  batch_size: 2
  num_workers: 1
  pin_memory: False
  single_channel: True
  tile_overlap: 0.0
  use_all_data: False

# ---------------------------- DATASET SPECIFIC OPTIONS -------------------------------------------
dataset_options:
  nx: {
    'No_000': 8192,
    'No_001': 8192,
  }
  ny: {
    'No_000': 8192,
    'No_001': 8192,
  }
  nz: {
    'No_000': 128,
    'No_001': 128,
  }
  num_samples_to_stitch: {
    'No_000': 1,
    'No_001': 1,
  }
  chunk_size: {
    'No_000': [128,128,128],
    'No_001': [128,128,128],
  }

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  batches_per_rank_epoch: {
  'No_000': 5120,
  'No_001': 5120,
  }
  dataset_group_list: '4:4'
