# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "bfloat16"
  checkpoint_path: "../../checkpoint/basic_ct/diffusion/base"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 8
  simple_ddp_size: 1
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False
  
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  loss_fn: "MSE"

  net:
    init_args:
      default_vars: [
        "ct_res1",
      ]
      tile_size: [64, 64, 64]
      patch_size: 4
      embed_dim: 768
      depth: 12
      num_heads: 12
      decoder_embed_dim: 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio: 4
      mlp_ratio_decoder: 4
      drop_path: 0.0
      linear_decoder: False
      twoD: True
      use_varemb: False
      adaptive_patching: False
      fixed_length: 196
      separate_channels: False
      num_time_steps: 1000

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "basic_ct"
  dict_root_dirs: {
    'ct1': '/lustre/orion/world-shared/nro108/anikat/dataset/Tr8_Training',
  }
  dict_start_idx: {
    'ct1': 0,
  }
  dict_end_idx: {
    'ct1': 1,
  }
  dict_buffer_sizes: {
    'ct1': 100,
  }
  num_channels_available: {
    'ct1': 1,
  }
  num_channels_used: {
    'ct1': 1,
  }
  dict_in_variables: {
    'ct1': [
     "ct_res1", 
    ],
  }
  batch_size: 2
  num_workers: 1
  pin_memory: False
  single_channel: True
  tile_overlap: 0.0
  use_all_data: False

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  batches_per_rank_epoch: {
    'ct1': 217088,
  }
  dataset_group_list: '8'
