# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32" #float 32 or bfloat16
  gpu_type: "amd" #amd or nvidia
  checkpoint_path: "../../checkpoint/basic_ct/unetr/base"
  resume_from_checkpoint: False
  checkpoint_filename: "epoch_0"
  use_pretrained_model: False
  pretrained_checkpoint_filename: ""
  save_frequency: 2

# ---------------------------- PARALLELISM ---------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 8
  tensor_par_size: 1

# ---------------------------- OPTIMIZER -----------------------------------------
optimizer:
  type: "AdamW"
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5

# ---------------------------- SCHEDULER -----------------------------------------
scheduler:
  type: "linear-warmup-cosine-annealing"
  warmup_epochs: 4
  warmup_start_lr: 1e-8
  eta_min: 1e-8

# ---------------------------- GRAD SCALER ---------------------------------------
grad_scaler:
  use_grad_scaler: False
  init_scale: 8192
  min_scale: 128
  growth_interval: 100

# ---------------------------- MODEL ---------------------------------------------
model:
  type: "UNETR"
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  drop_path: 0.0
  drop_rate: 0.0
  use_channel_aggregation: False

  num_classes: 4
  linear_decoder: False
  feature_size: 16
  skip_connection: True
  
# ---------------------------- TILING --------------------------------------------
tiling:
  do_tiling: True
  div: 4
  tile_overlap: 0.0
  use_all_data: False

# ---------------------------- AP ------------------------------------------------

ap:
  do_ap: True
  fixed_length: 512
  separate_channels: False
  use_adaptive_pos_emb: True
  
# ---------------------------- DATA ----------------------------------------------
data:
  dataset: "basic_ct"
  img_size: [256, 256, 256] #Can be 2D or 3D, on todo list create capability where this isn't required, but can be read determined base on the reading the raw data.
  twoD: False #If true when img_size is 3D, dataloader slices on the z dimension. If data is 2D, this variable will be ignored and default to True
  patch_size: 4 #If non-adaptive patching this will change sequence length, if adaptive patching this will determine the common representation across all adaptive patches
  dict_root_dirs: {
    'ct1': '/lustre/orion/world-shared/nro108/anikat/dataset/Tr8_Training',
  }
  num_channels: {
    'ct1': 1,
  } #Important to define because not all datasets need to have the same channels or amount of channels when using variable aggregation depending on the training task chosen
  dict_in_variables: {
    'ct1': [
     "ct_res1", 
    ],
  } #Needs to match the order of the channels in the raw data files, if using variable aggregation. If not using variable aggregation you may just fill this in with placeholders using the correct amount of channels as this will not be used
  
# ---------------------------- DATALOADER ----------------------------------------
dataloader:
  type: "iterative_dataloader"
  dict_start_idx: {
    'ct1': 0,
  }
  dict_end_idx: {
    'ct1': 1,
  }
  dict_buffer_sizes: {
    'ct1': 20,
  }
  batch_size: 2
  num_workers: 0
  pin_memory: False
