# ---------------------------- TRAINER -------------------------------------------
trainer:
  max_epochs: 600
  data_type: "float32"
  checkpoint_path: "../../checkpoint/s8d_2d_label/sap/base"
  checkpoint_filename: "multi_last"
  checkpoint_filename_for_loading: "multi_last_odd" #multi_last_odd or multi_last_even

  resume_from_checkpoint: False
  use_pretrained_mae_model: False
  mae_checkpoint_path: "../../checkpoint/s8d_2d_label/mae/base"
  mae_checkpoint_filename: "multi_last_odd" #multi_last_odd or multi_last_even

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  fsdp_size: 1
  simple_ddp_size: 32
  tensor_par_size: 1
  seq_par_size: 1
  cpu_offloading: False
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0001
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8

  net:
    init_args:
      default_vars: [
        "ct_res1",
      ]
      tile_size: [8192,8192,10]
      patch_size: 8
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4
      drop_path: 0.0
      twoD: True
      use_varemb: False
      adaptive_patching: True
      fixed_length: 4096
      separate_channels: False

      decoder_embed_dim: 576
      decoder_depth: 8
      decoder_num_heads: 16
      mlp_ratio_decoder: 4
      linear_decoder: False
      mask_ratio: 0.75

# ---------------------------- DATA -------------------------------------------
data:
  dataset: "s8d_2d_label"
  dict_root_dirs: {
    '100': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/100',
    '90': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/90',
    '80': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/80',
    '70': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/70',
    '60': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/60',
    '50': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/50',
    '40': '/lustre/orion/lrn075/world-shared/Riken_XCT_Simulated_Data_REFACTOR/8192x8192xN_Simulations/combined_morefiles/FBPs/40',
  }
  dict_start_idx: {
    '100': 0,
    '90': 0,
    '80': 0,
    '70': 0,
    '60': 0,
    '50': 0,
    '40': 0,
  }
  dict_end_idx: {
    '100': 1,
    '90': 1,
    '80': 1,
    '70': 1,
    '60': 1,
    '50': 1,
    '40': 1,
  }
  dict_buffer_sizes: {
    '100': 100,
    '90': 100,
    '80': 100,
    '70': 100,
    '60': 100,
    '50': 100,
    '40': 100,
  }
  num_channels_available: {
    '100': 1,
    '90': 1,
    '80': 1,
    '70': 1,
    '60': 1,
    '50': 1,
    '40': 1,
  }
  num_channels_used: {
    '100': 1,
    '90': 1,
    '80': 1,
    '70': 1,
    '60': 1,
    '50': 1,
    '40': 1,
  }
  dict_in_variables: {
    '100': [
     "ct_res1", 
    ],
    '90': [
     "ct_res1", 
    ],
    '80': [
     "ct_res1", 
    ],
    '70': [
     "ct_res1", 
    ],
    '60': [
     "ct_res1", 
    ],
    '50': [
     "ct_res1", 
    ],
    '40': [
     "ct_res1", 
    ],
  }
  batch_size: 1
  num_workers: 1
  pin_memory: False
  single_channel: True
  tile_overlap: 0.0
  use_all_data: False
  num_classes: 5

# ---------------------------- LOAD BALANCING -------------------------------------------
load_balancing:
  batches_per_rank_epoch: {
  '100': 220,
  '90': 210,
  '80': 240,
  '70': 230,
  '60': 210,
  '50': 260,
  '40': 360,
  }
  dataset_group_list: '8:5:4:6:5:3:1'
